name: Terraform apply

on:
  issue_comment:
    types: [created]

jobs:
  apply:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/apply') && (github.actor == 'tru2dagame' || github.actor == 'dada8397')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: terraform_init.yaml
          pr: ${{ github.event.issue.number }}
          name: plans_${{ github.event.issue.number }}
      - run: cat plan_aaa.out
